### ISSUE TITLE
Default values for unchanged form

### ISSUE THREAD

**Issue by PlkMarudny** [idris-maps/svelte-parts#7]
When a form is created from data and submitted, only changed values are evaluated and sent back to the server, for example:
````
"fields": [
                            {
                                "type": "text",
                                "property": "upper_line",
                                "label": "Upper Line",
                                "notRequired": true
                            },
                            {
                                "type": "text",
                                "property": "bottom_line",
                                "label": "Bottom Line",
                                "notRequired": true
                            },
                            {
                                "type": "date",
                                "property": "onair_date",
                                "label": "Date"
                            },
                            {
                                "type": "checkbox",
                                "property": "12h",
                                "label": "AM/PM",
                                "value": true
                            },
                            {
                            "type": "radio",
                            "property": "pill",
                            "label": "Choose your pill",
                            "options": [
                                "red",
                                "blue"
                            ],
                            "value": ""
                            }
                        ]
````

Generates the following form:
![image](https://user-images.githubusercontent.com/4361591/133257995-7549ca88-2586-4e5b-b7b6-241905718717.png)

Pressing "submit" after setting up a date (required) produces:
![image](https://user-images.githubusercontent.com/4361591/133258260-1d346a29-bf4f-4469-b68d-36873a175896.png)

It does not seem possible to receive all the fields with the default values instead (but it would be nice to get them)

![image](https://user-images.githubusercontent.com/4361591/133258489-a386630e-f2bb-42c0-b4b5-458fe1c04ebe.png)

**Comment by idris-maps** [comment]
Thank you @PlkMarudny 
Should be fixed now. If you add a default `value` of `''`, it will be returned.
Here is your example in the svelte REPL: https://svelte.dev/repl/3a3b457d16f34e40a55ed5b490cef1b8?version=3.43.1
